### ISSUE TITLE
Rewiew PCB V5.0

### ISSUE THREAD

**Issue by andz82** [bt-trx/dev-board#25]

**Comment by dl1com** [comment]
- [ ] Proposal from Xaver: Add kerko in Vin path. Why yes/no?
- [x] Add Pullup (10k) for Hardware version indicator
- [ ] gnda groundplane shall end at the transformers, currently it's also under the diff signals of wt32, which is pwrgnd domain.

**Comment by andz82** [comment]
**Proposal from Xaver: Add kerko in Vin path. Why yes/no?**
C1 on ESP32 DevKit C (10uF) should be fine
